spring:
  datasource:
    url: jdbc:h2:mem:usersdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

app:
  jwt:
    secret: verySecretKeyThatYouShouldChangeInProd
    expiration-ms: 3600000
  regex:
    email: "^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,6}$"
    password: "^(?=.{8,12}$)(?=[^A-Z]*[A-Z][^A-Z]*$)(?=[^0-9]*[0-9][^0-9]*[0-9][^0-9]*$)[A-Za-z0-9]+$"

logging:
  level:
    root: INFO
